version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../:/workspaces/app
      - node_modules:/workspaces/app/client/node_modules
    ports:
      - "3000:3000"
      - "22:22"
    environment:
      - NODE_ENV=development
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: